const products = [
  {
    _id: "621235e59540445b3sdfe9s0",
    name: "AKRacing Core Series EX Gaming Chair ",
    image: "/images/AKRacingCoreSeriesEx.jpg",
    description:
      "Features a wide metal frame with anti corrorsive coating and high-density cold-cured foam padding for maximum comfort and durability.",
    brand: "AKRacing",
    category: "AKRACING",
    price: 100.95,
    rating: 5,
    numReviews: 1,
    isNew: true,
    reviews: [],
    stock: 700000,
  },
  {
    _id: "636985e59540445b3c45e6af",
    name: "GTRacing Gaming Chair",
    image: "/images/GTRacingGamingChair.jpg",
    description:
      "Competitively priced gaming chair ideal for students on a budget. Built on a metal frame with synthetic leather converings.",
    brand: "GTRacing",
    category: "GTRacing",
    price: 179.99,
    rating: 3,
    numReviews: 1,
    isNew: false,

    reviews: [],
    stock: 700000,
  },
  {
    _id: "6369860d9540445b3c45e6b1",
    name: "Darkecho Massage Gaming Chair with foot rest",
    image: "/images/DarkechoMassage-GamingChair.jpg",
    description: "The perfect combination of value and comfort. Features a pull-out foot rest underneath the chair.",
    brand: "Darkecho",
    category: "Darkecho",
    price: 179.99,
    rating: 5,
    numReviews: 0,
    isNew: false,
    reviews: [],
    stock: 7000000,
  },
  {
    _id: "6369863c9540445b3c45e6b3",
    name: "Darkecho Massage Gaming Chair with foot rest, vintage leather edition",
    image: "/images/DarkechoMassage-GamingChair.jpg",
    description:
      "A luxurious upgradefrom the basic massage gaming chair with foot rest. Features real leather, for the refined gamer.",
    brand: "Darkecho",
    category: "Darkecho",
    price: 279.99,
    rating: 5,
    numReviews: 0,
    isNew: false,
    reviews: [],
    stock: 700000,
  },
  {
    _id: "636986579540445b3c45e6b5",
    name: "Darkecho Massage Gaming Chair, big and tall edition",
    image: "/images/DarkechoMassageBigandTall.jpg",
    description:
      "Built for gamers 6' or taller. With an extra 6-inch back rest and 2 inches of extra space between armrests compared to regular gaming chairs.",
    brand: "Darkecho",
    category: "Darkecho",
    price: 269.99,
    rating: 4,
    numReviews: 1,
    isNew: false,

    reviews: [],
    stock: 700000,
  },
  {
    _id: "636986749540445b3c45e6b7",
    name: "DarkechoHighSpeed",
    image: "/images/DarkechoHighSpeed.jpg",
    description:
      "Lightweight, high speed and low drag. This chair weighs less than 20 pounds and is ideal for gamers who can't sit still in one room while they game.",
    brand: "Darkecho",
    category: "Darkecho",
    price: 178.99,
    rating: 5,
    numReviews: 0,
    isNew: false,
    stock: 700000,
  },
  {
    _id: "63804a5079636c2ced47757d",
    name: "Sukida Massage Gaming Chair",
    image: "/images/SukidaMassage.jpg",
    brand: "Sukida",
    category: "Sukida",
    description:
      "Features 30% more padding than typical gaming chairs, and a retractable foot rest underneath the chair.",
    rating: 0,
    numReviews: 0,
    price: 179.99,
    stock: 70000000,
    isNew: true,
    reviews: [],
  },
  {
    _id: "6381275e8e8648e00b7c82f7",
    name: "Sukida Massage Gaming Chair limited edition",
    image: "/images/SukidaMassageLimited.jpg",
    brand: "Sukida",
    category: "Sukida",
    description:
      "Limited edition Sukida Massage Gaming Chair in blue finish. Features 30%. more padding than typical gaming chairs, a retractable foot rest underneath the table.",
    rating: 0,
    numReviews: 0,
    price: 359.99,
    stock: 7000000,
    isNew: true,
    reviews: [],
  },
  {
    _id: "63895d3b2a3e062504353022",
    name: "Sukida Gaming Chair for Adults",
    image: "/images/SukidaGamingChairsForAdults.jpg",
    brand: "Sukida",
    category: "Sukida",
    description:
      "Sukida Gaming Chair built specficially for adults. For when you gotta look professional, and game at the same time.",
    rating: 5,
    numReviews: 1,
    price: 399.99,
    stock: 7000000,
    isNew: true,
    reviews: [],
  },
];

export default products;
